/** Version requirement for a remote Swift package (mirrors Xcode's model). */
export type SwiftPackageRequirement =
  | { kind: 'upToNextMajorVersion'; minimumVersion: string }
  | { kind: 'upToNextMinorVersion'; minimumVersion: string }
  | { kind: 'versionRange'; minimumVersion: string; maximumVersion: string }
  | { kind: 'exactVersion'; version: string }
  | { kind: 'branch'; branch: string }
  | { kind: 'revision'; revision: string };

/**
 * Target(s) a package's products attach to. A single string keeps the common
 * "main app only" case ergonomic; an array attaches to every named target —
 * required when a CocoaPods subspec (e.g. a Recording pod that imports the
 * SPM-provided framework) needs visibility into the same SPM products as the
 * main app.
 */
export type SpmTargetRef = string | readonly string[];

export interface SpmRemotePackage {
  /** Repository URL, e.g. "https://github.com/apple/swift-collections". */
  url: string;
  requirement: SwiftPackageRequirement;
  /** Product names to link (e.g. ["Collections"]). */
  products: string[];
  /**
   * Target(s) on the **main project's** `<App>.xcodeproj` to attach products
   * to (app target, extension targets). Defaults to the main app target when
   * neither `target` nor `podTarget` is set.
   */
  target?: SpmTargetRef;
  /**
   * Target(s) on the **CocoaPods-generated `Pods.xcodeproj`** to attach
   * products to. Wired via a Podfile `post_install` block (`Pods.xcodeproj`
   * is regenerated by every `pod install`, so live pbx ops at finalized
   * would be wiped). Use this when a CocoaPods subspec/standalone pod
   * (e.g. `OnemimirNativeIOSRecording`) compiles Swift sources that need
   * `import` access to the SPM-provided framework.
   */
  podTarget?: SpmTargetRef;
}

export interface SpmLocalPackage {
  /** Path to the local package relative to the Xcode project (ios/). */
  path: string;
  products: string[];
  /** See `SpmRemotePackage.target`. */
  target?: SpmTargetRef;
  /** See `SpmRemotePackage.podTarget`. */
  podTarget?: SpmTargetRef;
}

/** The manifest slice this package consumes. */
export interface IosSpmManifest {
  swiftPackages?: {
    remote?: SpmRemotePackage[];
    local?: SpmLocalPackage[];
  };
}
