import WidgetKit
import SwiftUI

struct Provider: TimelineProvider {
  func placeholder(in context: Context) -> SimpleEntry {
    SimpleEntry(date: Date())
  }

  func getSnapshot(in context: Context, completion: @escaping (SimpleEntry) -> Void) {
    completion(SimpleEntry(date: Date()))
  }

  func getTimeline(in context: Context, completion: @escaping (Timeline<SimpleEntry>) -> Void) {
    completion(Timeline(entries: [SimpleEntry(date: Date())], policy: .never))
  }
}

struct SimpleEntry: TimelineEntry {
  let date: Date
}

struct AcmeWidgetEntryView: View {
  var entry: Provider.Entry

  var body: some View {
    Text(entry.date, style: .time)
  }
}

struct AcmeWidget: Widget {
  let kind: String = "AcmeWidget"

  var body: some WidgetConfiguration {
    StaticConfiguration(kind: kind, provider: Provider()) { entry in
      AcmeWidgetEntryView(entry: entry)
    }
    .configurationDisplayName("Acme")
    .description("Example widget generated by expo-workspaces.")
  }
}
